apiVersion: v2
name: express-botx
description: eXpress BotX API gateway
type: application
version: 0.28.2
appVersion: "0.31.2"
home: https://github.com/lavr/express-botx
sources:
  - https://github.com/lavr/express-botx
maintainers:
  - name: lavr
