bots:
  mybot:
    host: env:BOT_HOST
    id: env:BOT_ID
    secret: env:BOT_SECRET

chats:
  dev:
    id: env:DEV_CHAT_ID
    bot: mybot

server:
  gitlab:
    senders:
      - name: default
        secret: env:GITLAB_WEBHOOK_TOKEN
        chats: [dev]
