{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "express-botx.fullname" . }}
  labels:
    {{- include "express-botx.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.yaml: |
    {{- if .Values.configRaw }}
    {{ tpl .Values.configRaw . | nindent 4 }}
    {{- else }}
    {{ toYaml .Values.config | nindent 4 }}
    {{- end }}
{{- end }}
